version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        container_name: sf4_nginx     
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        container_name: sf4_php
        expose:
            - 9000
        volumes:
            - ./api:/var/www/html
        links:
            - mongo
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=192.168.99.1"

###########################
# Setup the Database (Mongo) container
###########################
    mongo:
        image: mongo
        container_name: sf4_mongo
        ports:
            - "27017:27017"
        restart: always